//! Cross-implementation tests: fixtures generated by the REAL Python
//! `anchor_v1` implementation (`fixtures/gen.py`) must verify identically in
//! Rust. Valid artifacts accept; every tampered/malformed variant rejects.

use anchor_v1_verifier::{canonical_json, cbor, checkpoint, cose, envelope, holder};
use base64::Engine;
use serde_json::Value;
use std::fs;
use time::{format_description::well_known::Rfc3339, OffsetDateTime};

fn fixture(name: &str) -> Value {
    let path = format!("{}/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap()
}

fn b64(s: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD.decode(s).unwrap()
}

fn b64_32(s: &str) -> [u8; 32] {
    let raw = b64(s);
    assert_eq!(raw.len(), 32);
    let mut out = [0u8; 32];
    out.copy_from_slice(&raw);
    out
}

fn hex_bytes(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

// ------------------------------------------------------------------ cose ---
#[test]
fn cose_cross_verify() {
    let fx = fixture("cose.json");
    let trusted: Vec<(Vec<u8>, [u8; 32])> = fx["trusted_keys"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| (b64(k), b64_32(v.as_str().unwrap())))
        .collect();

    // Valid message: payload and kid round-trip.
    let (payload, kid) = cose::verify(
        &b64(fx["valid"]["message_b64"].as_str().unwrap()),
        &trusted,
        b"",
    )
    .expect("valid COSE message must verify");
    assert_eq!(payload, b64(fx["valid"]["payload_b64"].as_str().unwrap()));
    assert_eq!(kid, b64(fx["valid"]["kid_b64"].as_str().unwrap()));

    // Every negative variant must fail.
    for name in [
        "tampered_sig",
        "tampered_payload",
        "noncanonical_protected",
        "wrong_kid",
        "extra_protected_field",
        "nonempty_unprotected",
        "wrong_alg",
        "truncated",
    ] {
        let msg = b64(fx[name]["message_b64"].as_str().unwrap());
        assert!(
            cose::verify(&msg, &trusted, b"").is_err(),
            "COSE variant {name} must be rejected"
        );
    }
}

// -------------------------------------------------------------- envelope ---
#[test]
fn envelope_cross_verify() {
    let fx = fixture("envelope.json");
    let trusted: Vec<(String, [u8; 32])> = fx["trusted_keys"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| (k.clone(), b64_32(v.as_str().unwrap())))
        .collect();
    let now = OffsetDateTime::parse(fx["now"].as_str().unwrap(), &Rfc3339).unwrap();

    let env = envelope::verify_envelope(
        &b64(fx["valid"]["message_b64"].as_str().unwrap()),
        &trusted,
        now,
        b"",
    )
    .expect("valid envelope must verify");
    assert_eq!(
        env.action_digest,
        fx["valid"]["action_digest"].as_str().unwrap()
    );
    assert_eq!(env.plane, "shell");
    assert_eq!(env.principal, "spiffe://example/agent");

    for name in ["expired", "not_yet_valid", "tampered", "extra_field"] {
        let msg = b64(fx[name]["message_b64"].as_str().unwrap());
        assert!(
            envelope::verify_envelope(&msg, &trusted, now, b"").is_err(),
            "envelope variant {name} must be rejected"
        );
    }
}

// ----------------------------------------------------------------- chain ---
#[test]
fn chain_cross_verify() {
    let fx = fixture("chain.json");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let chain: Vec<Value> = case["chain"].as_array().unwrap().clone();
        let bs = &case["bootstrap"];
        let bootstrap = checkpoint::TrustedSigner {
            key_id: bs["key_id"].as_str().unwrap().to_owned(),
            public_key: b64_32(bs["public_key_b64"].as_str().unwrap()),
        };
        let anc = &case["anchor"];
        let anchor_pk = b64_32(anc["public_key_b64"].as_str().unwrap());
        let log: Vec<Value> = anc["log"].as_array().unwrap().clone();
        let trust = checkpoint::AnchorTrust {
            key_id: anc["key_id"].as_str().unwrap(),
            public_key: &anchor_pk,
            log: Some(&log),
        };
        let expected = case["expected"].as_bool().unwrap();
        assert_eq!(
            checkpoint::verify_checkpoint_chain(&chain, &bootstrap, &trust),
            expected,
            "chain case {name}"
        );
    }
}

// ------------------------------------------------------------- inclusion ---
#[test]
fn inclusion_cross_verify() {
    let fx = fixture("inclusion.json");
    for case in fx["cases"].as_array().unwrap() {
        let expected = case["expected"].as_bool().unwrap();
        assert_eq!(
            checkpoint::verify_inclusion(&case["checkpoint"], &case["event"], &case["proof"]),
            expected,
            "inclusion case failed"
        );
    }
}

// ---------------------------------------------------------------- holder ---
#[test]
fn holder_cross_verify() {
    let fx = fixture("holder.json");
    for (name, case) in fx.as_object().unwrap() {
        let ok = holder::verify_holder_proof(
            &b64(case["pubkey_b64"].as_str().unwrap()),
            case["capability_id"].as_str().unwrap(),
            &b64(case["challenge_b64"].as_str().unwrap()),
            &b64(case["proof_b64"].as_str().unwrap()),
        )
        .is_ok();
        assert_eq!(ok, case["expected"].as_bool().unwrap(), "holder case {name}");
    }
}

// --------------------------------------------------------------- canonical ---
#[test]
fn canonical_json_byte_exact() {
    let fx = fixture("canonical.json");
    for (i, case) in fx.as_array().unwrap().iter().enumerate() {
        let got = hex::encode(canonical_json::canonical_bytes(&case["value"]).unwrap());
        assert_eq!(got, case["expected_hex"].as_str().unwrap(), "canonical case {i}");
    }
}

// ------------------------------------------------------------------ cbor ---
#[test]
fn cbor_vectors() {
    let fx = fixture("cbor.json");
    for vec in fx["valid"].as_array().unwrap() {
        let name = vec["name"].as_str().unwrap();
        let bytes = hex_bytes(vec["hex"].as_str().unwrap());
        // Strict decode accepts...
        let value = cbor::loads(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        // ...and re-encoding the canonical value is byte-identical.
        let re = cbor::dumps(&value).unwrap();
        assert_eq!(re, bytes, "cbor round-trip {name}");
    }
    for (name, hexstr) in fx["invalid"].as_array().unwrap().iter().map(|v| {
        (
            v[0].as_str().unwrap().to_owned(),
            v[1].as_str().unwrap().to_owned(),
        )
    }) {
        let bytes = hex_bytes(&hexstr);
        assert!(cbor::loads(&bytes).is_err(), "cbor invalid vector {name}");
    }
}
